name: Build CloudStream Extension

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Build Extension
        run: ./gradlew assembleRelease

      - name: Upload .cs3
        uses: actions/upload-artifact@v3
        with:
          name: AnimeSama.cs3
          path: build/libs/*.cs3
